"""
Custom Prometheus Metrics — InnerCircle AGI Observability Layer
───────────────────────────────────────────────────────────────
Exposes domain-level metrics at /metrics (Prometheus format).
Dashboards: Import into Grafana via Prometheus datasource.
"""

from prometheus_client import Counter, Histogram, Gauge

# ── Council / Agent Metrics ───────────────────────────────────
COUNCIL_QUERIES_TOTAL = Counter(
    "innercircle_council_queries_total",
    "Total number of council queries processed",
)

AGENT_QUERY_COUNTER = Counter(
    "innercircle_agent_queries_total",
    "Queries per council agent",
    ["agent_role"],   # life_coach / investment / performance / career / health / synthesizer
)

OLLAMA_LATENCY = Histogram(
    "innercircle_ollama_response_seconds",
    "Ollama LLM response latency in seconds",
    buckets=[1, 2, 5, 10, 20, 30, 60, 120],
)

INSIGHTS_GENERATED_TOTAL = Counter(
    "innercircle_insights_generated_total",
    "Total proactive insights generated by Celery",
)

INSIGHTS_READ_TOTAL = Counter(
    "innercircle_insights_read_total",
    "Total insights marked as read by users",
)

# ── Auth Metrics ──────────────────────────────────────────────
AUTH_REGISTRATIONS = Counter(
    "innercircle_auth_registrations_total",
    "Total successful user registrations",
)

AUTH_LOGINS = Counter(
    "innercircle_auth_logins_total",
    "Total successful logins",
)

AUTH_FAILURES = Counter(
    "innercircle_auth_failures_total",
    "Total failed authentication attempts",
    ["reason"],   # invalid_credentials / inactive_account
)

# ── System Metrics ────────────────────────────────────────────
ACTIVE_USERS_GAUGE = Gauge(
    "innercircle_registered_users_total",
    "Total number of registered users",
)

ACTIVE_SESSIONS_GAUGE = Gauge(
    "innercircle_active_sessions_total",
    "Total number of conversation sessions",
)
